### ISSUE TITLE
Checklist do report

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2021-007-JB#7]
- [ ] Title
- [ ] Objective
- [ ] Context (from SAP)
- [ ] Data & Methods (from SAP)
- [ ] Conclusions match the results
- [ ] Observations
- [ ] remove watermark
- [ ] update TOC
- [ ] render private + public version

**Comment by philsf** [comment]
closed in #14
